// Why: ambient types for the State API globals that the shared preamble helper
// (src/shared/state-api.ts) puts on globalThis. Kept as a global script (no
// imports/exports) so the interfaces below are ambient and usable from any
// component source. Contract: AGENTS.md "State API".

/** Per-instance bound API: `document.querySelector('#x').api.setState('open')`. */
interface DefussShadcnComponentApi {
  setState(stateName: string, config?: Record<string, unknown>): void;
  getState(): DefussShadcnComponentState;
}

interface DefussShadcnComponentState {
  /** Declared state name ('default' unless setState() was called). */
  name: string;
  /** Free-form config passed to setState(); components may ignore it. */
  config: Record<string, unknown>;
}

/** Options accepted by the toast imperative API (see src/components/toast/toast.ts). */
interface DefussShadcnToastOptions {
  title?: string;
  description?: string;
  variant?: string;
  duration?: number;
  action?: { label: string; onClick: () => void };
  onDismiss?: () => void;
}

/** Public imperative API a component may expose as `df$.{name}`. */
interface DefussShadcnToastApi {
  show(options: string | DefussShadcnToastOptions): HTMLElement;
  success(options: string | DefussShadcnToastOptions): HTMLElement;
  warning(options: string | DefussShadcnToastOptions): HTMLElement;
  info(options: string | DefussShadcnToastOptions): HTMLElement;
  error(options: string | DefussShadcnToastOptions): HTMLElement;
  dismiss(): void;
}

/** Docs search index entry, generated by scripts/lib/search-index.ts and
 * loaded by js/search-index.js (doc site only — not a component contract). */
interface DefussShadcnSearchEntry {
  /** entry title */
  t: string;
  /** target href: `page.html` or `page.html#section` */
  h: string;
  /** group heading: nav section for pages, page label for their sections */
  s: string;
}

/** Doc-site namespace: generated search index + SPA hooks (doc site only). */
interface DefussShadcnDocsNamespace {
  /** Docs search index (js/search-index.js, generated). */
  searchIndex?: DefussShadcnSearchEntry[];
  [key: string]: unknown;
}

/**
 * The component-shared layer core installs at `df$.shadcn.shared` (§2.2 of
 * plans/defuss-query-morph-integration.md) — the functions every emitted component
 * binds to instead of inlining copies. `abi` is the release stamp components
 * guard on (src/shared/version.ts).
 */
interface DefussShadcnShared {
  abi: string;
  defussGlobals(): DefussShadcnRegistry;
  safeShowPopover(el: HTMLElement): void;
  /** the installed callable query factory (typed via defuss-query/core) */
  defussQuery(): import('defuss-query/core').DfDollar;
  /** trailing-edge debounce with flush()/cancel() (src/shared/debounce.ts) */
  debounce<A extends unknown[]>(
    fn: (...args: A) => void,
    wait: number,
  ): ((...args: A) => void) & { flush(): void; cancel(): void };
}

/**
 * Registry populated by components: `df$.shadcn.dialogApi`,
 * `df$.shadcn.toast`, … — the namespace core prepares and components own.
 */
interface DefussShadcnRegistry {
  [key: `${string}Api`]: DefussShadcnComponentApi | undefined;
  [key: `${string}States`]: readonly string[] | undefined;
  toast?: DefussShadcnToastApi;
  docs?: DefussShadcnDocsNamespace;
  shared?: DefussShadcnShared;
  [key: string]: unknown;
}

/** `document.querySelector` alias — defined once, by the shared layer. */
declare var $: typeof document.querySelector;
/**
 * The callable query runtime (defuss-query + defuss-morph) installed ONCE by
 * core's guarded bootstrap (dist/components/core.js, embedded first in all.js)
 * — typed with query's own exported types, never re-declared by hand.
 */
declare var df$: import('defuss-query/core').DfDollar & { shadcn: DefussShadcnRegistry };

interface HTMLElement {
  /** Present on elements whose component bound the state API. */
  api?: DefussShadcnComponentApi;
  /** Config from the last setState() call (state name lives in dataset.stateName). */
  _stateConfig?: Record<string, unknown>;
  /** Resizer-only: authored [width, height] px snapshot at init, for 'default'. */
  _defaultSize?: [number, number];
  /** Accordion-only: authored open flags snapshotted at init, for the 'default' state. */
  _defaultOpen?: boolean[];
  /** Accordion-only: set while triggerStateChange() is applying (suspends enforcement). */
  _applying?: boolean;
  /** Accordion-only: generation counter so queued toggle events can't clear a newer _applying. */
  _applyGen?: number;
}

interface HTMLDialogElement {
  /** Trigger to refocus when the dialog closes (set by dialog.js). */
  _trigger?: HTMLElement | null;
}
