// Why: ambient types for the State API globals that the shared preamble helper
// (src/shared/state-api.ts) puts on globalThis. Kept as a global script (no
// imports/exports) so the interfaces below are ambient and usable from any
// component source. Contract: AGENTS.md "State API".

/** Per-instance bound API: `document.querySelector('#x').api.setState('open')`. */
interface DefussShadcnComponentApi {
  setState(stateName: string, config?: Record<string, unknown>): void;
  getState(): DefussShadcnComponentState;
  /** The markup of a state (default: the current one) - AGENTS.md "State
   *  API" → render; required of every JS component (RENDER_LEGACY shrinks). */
  render?(state?: DefussShadcnComponentState): string;
}

/** Registry-level State API (`df$.shadcn.{name}Api`): the element comes first
 * (AGENTS.md "State API" rule 4) - el.api is the bound per-element form. */
interface DefussShadcnRegistryApi {
  setState(el: HTMLElement, stateName: string, config?: Record<string, unknown>): void;
  getState(el: HTMLElement): DefussShadcnComponentState;
  /** Pure state → markup: render(getState(el)) reproduces el 1:1. */
  render?(state: DefussShadcnComponentState): string;
}

interface DefussShadcnComponentState {
  /** Declared state name ('default' unless setState() was called). */
  name: string;
  /** Free-form config passed to setState(); components may ignore it. */
  config: Record<string, unknown>;
  /** The authored markup (snapshotted at init) render() starts from. */
  model?: import('../shared/render.js').ElementModel;
}

/** Options accepted by the toast imperative API (see src/components/toast/toast.ts). */
interface DefussShadcnToastOptions {
  title?: string;
  description?: string;
  variant?: string;
  duration?: number;
  action?: { label: string; onClick: () => void };
  onDismiss?: () => void;
}

/** Public imperative API a component may expose as `df$.{name}`. */
interface DefussShadcnToastApi {
  show(options: string | DefussShadcnToastOptions): HTMLElement;
  success(options: string | DefussShadcnToastOptions): HTMLElement;
  warning(options: string | DefussShadcnToastOptions): HTMLElement;
  info(options: string | DefussShadcnToastOptions): HTMLElement;
  error(options: string | DefussShadcnToastOptions): HTMLElement;
  dismiss(): void;
}

/** Docs search index entry, generated by scripts/lib/search-index.ts and
 * loaded by js/search-index.js (doc site only - not a component contract). */
interface DefussShadcnSearchEntry {
  /** entry title */
  t: string;
  /** target href: `page.html` or `page.html#section` */
  h: string;
  /** group heading: nav section for pages, page label for their sections */
  s: string;
}

/** Doc-site namespace: generated search index + SPA hooks (doc site only). */
interface DefussShadcnDocsNamespace {
  /** Docs search index (js/search-index.js, generated). */
  searchIndex?: DefussShadcnSearchEntry[];
  [key: string]: unknown;
}

/**
 * The component-shared layer core installs at `df$.shadcn.shared` (§2.2 of
 * plans/defuss-query-morph-integration.md) - the functions every emitted component
 * binds to instead of inlining copies. `abi` is the release stamp components
 * guard on (src/shared/version.ts).
 */
interface DefussShadcnShared {
  abi: string;
  defussGlobals(): DefussShadcnRegistry;
  safeShowPopover(el: HTMLElement): void;
  /** the installed callable query factory (typed via defuss-query/core) */
  defussQuery(): import('defuss-query/core').DfDollar;
  /** trailing-edge debounce with flush()/cancel() (src/shared/debounce.ts) */
  debounce<A extends unknown[]>(
    fn: (...args: A) => void,
    wait: number,
  ): ((...args: A) => void) & { flush(): void; cancel(): void };
  /** the locale to format numbers / dates for an element: its nearest [lang], else the document's, else 'en' (src/shared/locale.ts) */
  textLocale(el?: Element | null): string;
  /** presentation machinery (src/shared/presentation.ts) - same functions ddf$ publishes */
  presentationScope: typeof import('../shared/presentation.js').presentationScope;
  animateCount: typeof import('../shared/presentation.js').animateCount;
  revealAttr: typeof import('../shared/presentation.js').revealAttr;
  clampIndex: typeof import('../shared/presentation.js').clampIndex;
  coerceIndex: typeof import('../shared/presentation.js').coerceIndex;
  /** motion controller (src/shared/motion.ts; keyframes in components/motion) */
  entrance: typeof import('../shared/motion.js').entrance;
  draw: typeof import('../shared/motion.js').draw;
  /** imperative animation engine (src/shared/anim.ts) - same registry as df$.anim */
  anim: typeof import('../shared/anim.js').anim;
  /** shared global-key API (src/shared/keys.ts) - one document keydown listener */
  bindGlobalKeys: typeof import('../shared/keys.js').bindGlobalKeys;
  /** did a key event come from a field being typed in? (for { editable: true } handlers) */
  isEditableTarget: typeof import('../shared/keys.js').isEditableTarget;
  /** theme resource loader (src/shared/theme-links.ts; theme/<id>.json sidecars) */
  loadTheme: typeof import('../shared/theme-links.js').loadTheme;
  /** render() machinery (src/shared/render.ts): authored-markup snapshot + state render */
  elementModel: typeof import('../shared/render.js').elementModel;
  renderModel: typeof import('../shared/render.js').renderModel;
}

/**
 * Registry populated by components: `df$.shadcn.dialogApi`,
 * `df$.shadcn.toast`, … - the namespace core prepares and components own.
 */
interface DefussShadcnRegistry {
  [key: `${string}Api`]: DefussShadcnRegistryApi | undefined;
  [key: `${string}States`]: readonly string[] | undefined;
  toast?: DefussShadcnToastApi;
  /** cookie consent (src/components/cookie-consent/cookie-consent.ts):
   * create(root, config) / get(root) / init() - and the State API registry */
  cookieConsent?: typeof import('../components/cookie-consent/cookie-consent.js').cookieConsent;
  /** panel imperative API (src/components/panel/panel.ts): every method takes
   * a .panel element, an id or a selector */
  panel?: {
    minimize(target: Element | string): Element | null;
    maximize(target: Element | string): Element | null;
    restore(target: Element | string): Element | null;
    toggle(target: Element | string): boolean;
  };
  /** window imperative API (src/components/window/window.ts): every method
   * takes a .window element, an id or a selector */
  win?: {
    create(options?: {
      title?: string; icon?: string; content?: Node | string; html?: string; statusbar?: string; id?: string;
      x?: number | string; y?: number | string; width?: number | string; height?: number | string;
      chrome?: 'windows' | 'mac' | 'linux' | 'retro'; resizable?: boolean; parent?: Element | string;
      focus?: boolean; flush?: boolean;
    }): HTMLDialogElement;
    open(target: Element | string, config?: { x?: number; y?: number }): HTMLDialogElement | null;
    close(target: Element | string): HTMLDialogElement | null;
    focus(target: Element | string): HTMLDialogElement | null;
    move(target: Element | string, x: number, y: number): { x: number; y: number } | null;
    resize(target: Element | string, width: number | string, height?: number | string): HTMLDialogElement | null;
    maximize(target: Element | string): HTMLDialogElement | null;
    minimize(target: Element | string): HTMLDialogElement | null;
    restore(target: Element | string): HTMLDialogElement | null;
    toggleMaximize(target: Element | string): HTMLDialogElement | null;
    active(): HTMLDialogElement | null;
    list(scope?: Element | string, all?: boolean): HTMLDialogElement[];
    cascade(scope?: Element | string, step?: number): void;
    tile(scope?: Element | string): void;
  };
  /** chart imperative API (src/components/chart/chart.ts): mount/instance/theme/deck stage */
  chart?: {
    mount: typeof import('../components/chart/chart.js').mount;
    instance: typeof import('../components/chart/chart.js').instance;
    theme: typeof import('../components/chart/chart.js').chartTheme;
    color: typeof import('../components/chart/chart.js').chartColor;
    deck: typeof import('../components/chart/chart.js').chartDeck;
  };
  /** mermaid imperative API (src/components/mermaid/mermaid.ts): lazy loader, renders, token theme */
  mermaid?: {
    load: (url?: string) => Promise<unknown>;
    render: (fig: HTMLElement) => Promise<boolean>;
    renderAll: () => Promise<boolean[]>;
    theme: typeof import('../components/mermaid/mermaid.js').mermaidTheme;
    url: string;
  };
  /** chart storytelling driver (src/components/chart/chart.ts) */
  chartStory?: typeof import('../components/chart/chart.js').chartStory;
  docs?: DefussShadcnDocsNamespace;
  shared?: DefussShadcnShared;
  /** imperative animation engine alias (same registry as df$.anim) */
  anim?: typeof import('../shared/anim.js').anim;
  [key: string]: unknown;
}

/** `document.querySelector` alias - defined once, by the shared layer. */
declare var $: typeof document.querySelector;
/**
 * The callable query runtime (defuss-query + defuss-morph) installed ONCE by
 * core's guarded bootstrap (dist/components/core.js, embedded first in all.js)
 * - typed with query's own exported types, never re-declared by hand.
 */
declare var df$: import('defuss-query/core').DfDollar & {
  shadcn: DefussShadcnRegistry;
  /** imperative animation engine, installed by core: df$.anim.fadeIn.play(el) */
  anim: typeof import('../shared/anim.js').anim;
};
/**
 * The shared library's public alias, installed ONCE by the same core bootstrap
 * as df$ (src/shared/presentation.ts → installDdf). Flat helper namespace for
 * imperative decks: `ddf$.presentation(el).next()`, `ddf$.animateCount(el)`,
 * `ddf$.revealAttr('up', 400)`. Never hand-written or replaced by components.
 */
declare var ddf$: import('../shared/presentation.js').DdfNamespace;

interface HTMLElement {
  /** Present on elements whose component bound the state API. */
  api?: DefussShadcnComponentApi;
  /** Config from the last setState() call (state name lives in dataset.stateName). */
  _stateConfig?: Record<string, unknown>;
  /** The authored markup render() starts from (snapshotted at init via elementModel). */
  _model?: import('../shared/render.js').ElementModel;
  /** Resizer-only: authored [width, height] px snapshot at init, for 'default'. */
  _defaultSize?: [number, number];
  /** Accordion-only: authored open flags snapshotted at init, for the 'default' state. */
  _defaultOpen?: boolean[];
  /** Accordion-only: set while triggerStateChange() is applying (suspends enforcement). */
  _applying?: boolean;
  /** Accordion-only: generation counter so queued toggle events can't clear a newer _applying. */
  _applyGen?: number;
  /** Mermaid-only: the theme (JSON) the diagram was last rendered with - re-render when it changes. */
  _mermaidTheme?: string;
}

interface HTMLDialogElement {
  /** Trigger to refocus when the dialog closes (set by dialog.js). */
  _trigger?: HTMLElement | null;
}
