/**
 * Why: besides the reference skill (skills/defuss-shadcn - how to write the
 * markup), the plugin ships three task skills an agent runs for a job:
 * shadcn-plan, shadcn-theme, shadcn-review - the defuss-shadcn layer on top of
 * whatever process method the project uses (defuss-vae's plan / review stay
 * theirs; the `shadcn-` prefix keeps both installable side by side in
 * harnesses that copy skills by folder name). Everything a task skill states
 * about the system - the component catalog, the token roles, the rules, the
 * guides, the checkers' vocabulary - is generated here from the sources, so a
 * skill cannot drift from the release it ships with: build.ts writes the
 * files, verify's `agent skills ↔ sources` gate compares them. Each skill
 * folder is self-contained (its references, its bundled .mjs tools), so a
 * skills-CLI install of one folder works; links into the package fall back
 * to raw files at the release tag.
 * VERIFIED: (verify `agent skills ↔ sources`; a probe made a stale SKILL.md, a
 * stray file and a TOKEN_RE drift fail by name) the folders cannot drift.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { componentDirs, componentFile } from '../../src/documentation/lib/component-dirs.ts';
import { componentSources } from './apps-files.ts';
import { buildVocab } from './markup-check.ts';
import { sectionSlug } from './sections.ts';
import { releaseInfo, skillEntries } from './skill-files.ts';
import { TYPE_NAMES } from './taxonomy.ts';
import { CONTRAST_PAIRS, THEME_TOKENS, TIER_LIMITS, tokenModes, type TokenGroup } from './theme-tokens.ts';

/** The task skills, in the order the docs list them. */
export const AGENT_SKILLS = ['shadcn-plan', 'shadcn-theme', 'shadcn-review'] as const;
export type AgentSkill = (typeof AGENT_SKILLS)[number];

/** Each skill's template (src/skills/<name>/) and generated folder (skills/<name>/). */
export const agentSkillTemplate = (name: AgentSkill) => `src/skills/${name}/SKILL_tpl.md`;
export const agentSkillDir = (name: AgentSkill) => `skills/${name}`;

const GENERATED = (what: string) => `<!-- GENERATED by scripts/lib/agent-skills.ts from ${what} - do not edit by hand; edit the source and rebuild. -->`;

type Nav = { label: string; href: string; children?: Nav[] };
type NavSection = { heading: string; items: Nav[] };

/** Frontmatter `description:` of a docs page. */
function pageDescription(root: string, slug: string): string {
  const file = join(root, 'src/documentation/pages', `${slug}.mdx`);
  if (!existsSync(file)) return '';
  const m = readFileSync(file, 'utf8').match(/^description:\s*["']?(.+?)["']?\s*$/m);
  return m ? m[1] : '';
}

/** references/catalog.md - every component by sidebar section: type, states, JS, when. */
export function catalogText(sections: readonly NavSection[], entries: ReturnType<typeof skillEntries>, hasJs: (name: string) => boolean, rawBase: string): string {
  const byName = new Map(entries.map((e) => [e.folder, e]));
  const lines = [
    GENERATED('every component-skill.md front matter + src/documentation/lib/nav.ts'),
    '',
    '# Component catalog',
    '',
    `${entries.length} components by sidebar section. **Type**: ${Object.entries(TYPE_NAMES).map(([k, v]) => `${k} ${v}`).join(', ')}. **States**: the names \`el.api.setState(name)\` accepts (\`default\` only = no state API). **JS**: ships a script.`,
    '',
    `Each name links to its component skill (markup, variants, sizes, ARIA, states) in the defuss-shadcn skill next to this one. Not there (this folder installed alone)? Fetch \`${rawBase}skills/defuss-shadcn/references/components/<name>.md\`.`,
  ];
  const listed = new Set<string>();
  for (const s of sections) {
    const names: string[] = [];
    const walk = (n: Nav) => {
      const slug = n.href.replace(/\.html$/, '');
      if (byName.has(slug) && !listed.has(slug)) names.push(slug);
      for (const c of n.children ?? []) walk(c);
    };
    s.items.forEach(walk);
    const own = entries.filter((e) => e.section === sectionSlug(s.heading) && !names.includes(e.folder)).map((e) => e.folder);
    const all = [...names, ...own];
    if (!all.length) continue;
    lines.push('', `## ${s.heading}`, '', '| Component | Type | States | JS | When |', '| --- | --- | --- | --- | --- |');
    for (const n of all) {
      listed.add(n);
      const e = byName.get(n)!;
      lines.push(`| [${e.name}](../../defuss-shadcn/references/components/${n}.md) \`${n}\` | ${e.type} | ${e.supportedStates.split(',').map((x) => x.trim()).join(', ')} | ${hasJs(n) ? 'yes' : '-'} | ${e.when.replace(/\|/g, '\\|')} |`);
    }
  }
  return `${lines.join('\n')}\n`;
}

/** references/rules.md - §2 of the reference skill, verbatim. */
export function rulesText(rootTemplate: string): string {
  const m = rootTemplate.match(/^## 2\. [^\n]*\n([\s\S]*?)(?=^## 3\.)/m);
  if (!m) throw new Error('src/SKILL_root_tpl.md lost its "## 2." rules section');
  return `${GENERATED('src/SKILL_root_tpl.md §2')}\n\n# Rules - every markup follows them\n${m[1].trimEnd()}\n`;
}

const GROUP_TITLES: Record<TokenGroup, string> = {
  surface: 'Surface / foreground pairs',
  utility: 'Utility',
  chart: 'Chart',
  sidebar: 'Sidebar',
  font: 'Typography',
  radius: 'Radius',
  shadow: 'Shadow scale',
  spacing: 'Spacing',
  tracking: 'Tracking',
  link: 'Links',
};

/** references/tokens.md - every theme token: role and default value per mode, plus the contrast pairs. */
export function tokensText(tokenCss: string): string {
  const { light, dark } = tokenModes(tokenCss);
  const cell = (v: string | undefined) => (v ? `\`${v.replace(/\|/g, '\\|')}\`` : '-');
  const lines = [
    GENERATED('scripts/lib/theme-tokens.ts + src/theme/utils/default-semantic-tokens.css'),
    '',
    '# Theme tokens',
    '',
    `A theme sets these ${Object.keys(THEME_TOKENS).length} custom properties - in \`:root\` (light) and \`.dark\` (dark) - and nothing else: components read no other token. Every colour token in both modes; \`--radius\` identical in both (the shape is part of the theme); \`--radius-sm/md/lg/xl\` are derived from \`--radius\`. Defaults below are the shipped token file's.`,
  ];
  for (const g of Object.keys(GROUP_TITLES) as TokenGroup[]) {
    lines.push('', `## ${GROUP_TITLES[g]}`, '', '| Token | Role | Light default | Dark default |', '| --- | --- | --- | --- |');
    for (const [t, d] of Object.entries(THEME_TOKENS)) if (d.group === g) lines.push(`| \`--${t}\` | ${d.role} | ${cell(light[t])} | ${cell(dark[t] ?? light[t])} |`);
  }
  lines.push('', '## Contrast pairs', '', 'Measured in both modes by `theme-check` (WCAG 2 contrast ratio). **reading**: body text - an error below 4.5:1. **text**: control labels - a warning below 4.5:1, an error below 3:1. **ui**: non-text indicators - a warning below 3:1.', '', '| Foreground | Background | Tier | Error below | Warning below |', '| --- | --- | --- | --- | --- |');
  for (const p of CONTRAST_PAIRS) {
    const [e, w] = TIER_LIMITS[p.tier];
    lines.push(`| \`--${p.fg}\` | \`--${p.bg}\` | ${p.tier} | ${e ? `${e}:1` : '-'} | ${w}:1 |`);
  }
  return `${lines.join('\n')}\n`;
}

/** references/guides.md - the Guides section: what each page settles, where to read it. */
export function guidesText(root: string, sections: readonly NavSection[], rawBase: string): string {
  const guides = sections.find((s) => s.heading === 'Guides');
  if (!guides) throw new Error('nav.ts lost its Guides section');
  const lines = [
    GENERATED('the Guides section of src/documentation/lib/nav.ts + each page\'s description'),
    '',
    '# Guides - the practices a review checks',
    '',
    `Each page is MDX with live examples: \`../../../src/documentation/pages/<page>.mdx\` from this file (plugin or npm install), else \`${rawBase}src/documentation/pages/<page>.mdx\`.`,
    '',
  ];
  for (const item of guides.items) {
    const slug = item.href.replace(/\.html$/, '');
    lines.push(`- **[${item.label}](../../../src/documentation/pages/${slug}.mdx)** - ${pageDescription(root, slug)}`);
    if (item.children?.length) lines.push(`  - ${item.children.map((c) => `[${c.label}](../../../src/documentation/pages/${c.href.replace(/\.html$/, '')}.mdx)`).join(', ')}`);
  }
  return `${lines.join('\n')}\n`;
}

/** One tool, bundled with its data into a single dependency-free ES module for Node. */
async function bundleTool(root: string, entry: string, data: unknown, version: string): Promise<string> {
  const result = await Bun.build({
    entrypoints: [join(root, entry)],
    target: 'node',
    format: 'esm',
    root,
    plugins: [{
      name: 'skill-data',
      setup(build) {
        build.onResolve({ filter: /^skill-data$/ }, () => ({ path: 'skill-data', namespace: 'skill-data' }));
        build.onLoad({ filter: /.*/, namespace: 'skill-data' }, () => ({ contents: `export default ${JSON.stringify(data)};`, loader: 'js' }));
      },
    }],
  });
  if (!result.success) throw new Error(`${entry}: ${result.logs.map(String).join('\n')}`);
  return `// GENERATED by scripts/lib/agent-skills.ts from ${entry} (defuss-shadcn ${version}) - do not edit; run with node.\n${await result.outputs[0].text()}`;
}

/** Every file of every task skill, keyed by repo-relative path. */
export async function buildAgentSkills(root: string): Promise<Map<string, string>> {
  const { version, rawBase } = releaseInfo(root);
  const { NAV } = (await import(join(root, 'src/documentation/lib/nav.ts'))) as { NAV: NavSection[] };
  const compsDir = join(root, 'src/components');
  const entries = skillEntries(compsDir);
  const hasJs = (n: string) => existsSync(componentFile(compsDir, n, `${n}.ts`));
  const tokenCss = readFileSync(join(root, 'src/theme/utils/default-semantic-tokens.css'), 'utf8');
  const counts = Object.keys(TYPE_NAMES).map((t) => `${entries.filter((e) => e.type === t).length} ${t}`).join(', ');
  const fill = (tpl: string) =>
    tpl.replaceAll('{{VERSION}}', version).replaceAll('{{RAW_BASE}}', rawBase).replaceAll('{{TOTAL}}', String(entries.length))
      .replaceAll('{{TYPE_COUNTS}}', counts).replaceAll('{{WITH_JS}}', String(entries.filter((e) => hasJs(e.folder)).length));
  const template = (name: AgentSkill) => fill(readFileSync(join(root, agentSkillTemplate(name)), 'utf8'));

  const catalog = catalogText(NAV, entries, hasJs, rawBase);
  const rules = rulesText(readFileSync(join(root, 'src/SKILL_root_tpl.md'), 'utf8'));
  const tokens = tokensText(tokenCss);
  const guides = guidesText(root, NAV, rawBase);

  const sources = componentSources();
  const skills = Object.fromEntries(componentDirs(compsDir).map(({ name }) => [name, readFileSync(componentFile(compsDir, name, 'component-skill.md'), 'utf8')]));
  const utilDir = join(root, 'src/theme/utils');
  const utilityCss = readdirSync(utilDir).filter((f) => f.endsWith('.css')).sort().map((f) => readFileSync(join(utilDir, f), 'utf8'));
  const vocab = buildVocab(sources, utilityCss, version, skills);

  const out = new Map<string, string>();
  const put = (name: AgentSkill, rel: string, text: string) => out.set(`${agentSkillDir(name)}/${rel}`, text);
  put('shadcn-plan', 'SKILL.md', template('shadcn-plan'));
  put('shadcn-plan', 'references/catalog.md', catalog);
  put('shadcn-plan', 'references/rules.md', rules);
  put('shadcn-plan', 'references/tokens.md', tokens);
  put('shadcn-plan', 'references/guides.md', guides);
  put('shadcn-theme', 'SKILL.md', template('shadcn-theme'));
  put('shadcn-theme', 'references/tokens.md', tokens);
  put('shadcn-theme', 'assets/theme-preview.html', fill(readFileSync(join(root, 'src/skills/shadcn-theme/theme-preview.html'), 'utf8')));
  put('shadcn-theme', 'scripts/theme-check.mjs', await bundleTool(root, 'scripts/skill-tools/theme-check.ts', { version, defaults: tokenModes(tokenCss) }, version));
  put('shadcn-review', 'SKILL.md', template('shadcn-review'));
  put('shadcn-review', 'references/rules.md', rules);
  put('shadcn-review', 'references/guides.md', guides);
  put('shadcn-review', 'references/catalog.md', catalog);
  put('shadcn-review', 'scripts/markup-check.mjs', await bundleTool(root, 'scripts/skill-tools/markup-check.ts', { version, vocab }, version));
  return out;
}

