/**
 * Why: src/documentation/ is a defuss-ssg project — the doc pages are authored
 * as MDX (pages/) with TSX components (lib/) and client runtime TS (runtime/),
 * while public/ is copied to the output root verbatim by the SSG build. None
 * of these authoring subtrees may be copied 1:1 into dist/ by build.ts or
 * flagged by verify's `dist 1:1` gate — this is the shared exclusion list.
 *
 * Mapping into dist/documentation/:
 *   pages/{name}.mdx        → {name}.html        (defuss-ssg renders)
 *   public/{path}           → {path}             (defuss-ssg copies)
 *   runtime/{name}.ts       → js/{name}.js       (tsc pre-step in build-docs)
 *   lib/, data/, config.ts  → (build-time only, never shipped)
 *   tsconfig.json           → (editor-only JSX types for .tsx, never shipped)
 */
export const DOCS_SSG_AUTHORING = ['pages', 'lib', 'runtime', 'public', 'data', 'config.ts', 'tsconfig.json', 'dist'];

/** True for src/documentation-relative paths that are SSG authoring inputs. */
export function isDocsSsgAuthoring(relFromSrcDocumentation: string): boolean {
  const r = relFromSrcDocumentation.replace(/\\/g, '/');
  return DOCS_SSG_AUTHORING.some((d) => r === d || r.startsWith(d + '/'));
}

/** True for src/-relative paths (e.g. "documentation/pages/badge.mdx"). */
export function isDocsSsgAuthoringSrc(relFromSrc: string): boolean {
  const r = relFromSrc.replace(/\\/g, '/');
  return r.startsWith('documentation/') && isDocsSsgAuthoring(r.slice('documentation/'.length));
}

/** Where a dist/documentation/{rel} artifact originates in src/documentation.
 *  Returns the src/-relative counterpart, or null for generated files. */
export function docsDistToSrc(relFromDistDocumentation: string): string | null {
  const r = relFromDistDocumentation.replace(/\\/g, '/');
  // generated by the search-index post plugin
  if (r === 'js/search-index.js') return null;
  // compiled runtime: dist/documentation/js/{n}.js ← runtime/{n}.ts
  const js = r.match(/^js\/(.+)\.js$/);
  if (js) return `documentation/runtime/${js[1]}.ts`;
  // static assets live in public/ (mirrored to output root by defuss-ssg)
  if (/^(css|fonts|images|videos)\//.test(r)) return `documentation/public/${r}`;
  // pages: {n}.html ← pages/{n}.mdx
  if (r.endsWith('.html')) return `documentation/pages/${r.replace(/\.html$/, '')}.mdx`;
  return null;
}
