/**
 * Why: src/documentation/ is a defuss-ssg project - the doc pages are authored
 * as MDX (pages/) with TSX components (lib/) and client runtime TS (runtime/),
 * while public/ is copied to the output root verbatim by the SSG build. None
 * of these authoring subtrees may be copied 1:1 into dist/ by build.ts or
 * flagged by verify's `dist 1:1` gate - this is the shared exclusion list.
 *
 * Mapping into dist/documentation/:
 *   pages/{name}.mdx        → {name}.html        (defuss-ssg renders)
 *   public/{path}           → {path}             (defuss-ssg copies)
 *   runtime/{name}.ts       → js/{name}.js       (tsc pre-step in build-docs)
 *   lib/, data/, config.ts  → (build-time only, never shipped)
 *   tsconfig.json           → (editor-only JSX types for .tsx, never shipped)
 */
/**
 * Why: pages whose deck is ALSO rendered chrome-free as deck-{slug}.html
 * (scripts/build-docs.ts, from the page's own example fence) so other pages
 * can frame it - the Getting Started rail embeds the flagship deck. One list,
 * shared by the producer and verify (dist 1:1 origin, sidebar exemption).
 */
export const STANDALONE_DECKS = ['system-in-numbers'];

/** Application scaffolds with a generated full-screen page (same idea as the
 *  standalone decks: one example fence, two ways to view it). */
export const STANDALONE_APPS = ['scaffold-admin-dashboard', 'scaffold-messenger', 'scaffold-issue-tracker', 'scaffold-notes', 'scaffold-status-page', 'scaffold-desktop', 'scaffold-document-editor'];

/** The generated full-screen page name for a scaffold page slug. */
export const standaloneAppFile = (slug: string): string => `app-${slug.replace(/^scaffold-/, '')}.html`;

/** Document templates with a generated full-screen reading page (the paper):
 *  like the scaffolds, one example fence and two ways to view it - but a
 *  document scrolls and loads the whole system (all.css + all.js), since it
 *  composes charts, diagrams and BibTeX rather than one app's components.
 *  VERIFIED: (paper-fullscreen.e2e) the page scrolls, its diagram, charts, BibTeX and
 *  icons initialize on all.js, and it follows the OS color scheme. */
export const STANDALONE_DOCS = ['paper'];

/** The generated full-screen page name for a document page slug. */
export const standaloneDocFile = (slug: string): string => `full-${slug}.html`;

/** The generated standalone page name for a deck page slug. */
export const standaloneDeckFile = (slug: string): string => `deck-${slug}.html`;

export const DOCS_SSG_AUTHORING = ['pages', 'lib', 'runtime', 'public', 'data', 'config.ts', 'tsconfig.json', 'dist'];

/** True for src/documentation-relative paths that are SSG authoring inputs. */
export function isDocsSsgAuthoring(relFromSrcDocumentation: string): boolean {
  const r = relFromSrcDocumentation.replace(/\\/g, '/');
  return DOCS_SSG_AUTHORING.some((d) => r === d || r.startsWith(d + '/'));
}

/** True for src/-relative paths (e.g. "documentation/pages/badge.mdx"). */
export function isDocsSsgAuthoringSrc(relFromSrc: string): boolean {
  const r = relFromSrc.replace(/\\/g, '/');
  return r.startsWith('documentation/') && isDocsSsgAuthoring(r.slice('documentation/'.length));
}

/** Where a dist/documentation/{rel} artifact originates in src/documentation.
 *  Returns the src/-relative counterpart, or null for generated files. */
export function docsDistToSrc(relFromDistDocumentation: string): string | null {
  const r = relFromDistDocumentation.replace(/\\/g, '/');
  // generated by the search-index post plugin
  if (r === 'js/search-index.js') return null;
  // compiled runtime: dist/documentation/js/{n}.js ← runtime/{n}.ts
  const js = r.match(/^js\/(.+)\.js$/);
  if (js) return `documentation/runtime/${js[1]}.ts`;
  // static assets live in public/ (mirrored to output root by defuss-ssg)
  if (/^(css|fonts|images|videos|templates)\//.test(r)) return `documentation/public/${r}`;
  // standalone decks: deck-{n}.html ← pages/{n}.mdx (its example fence)
  const deck = STANDALONE_DECKS.find((s) => r === standaloneDeckFile(s));
  if (deck) return `documentation/pages/${deck}.mdx`;
  // full-screen scaffolds: app-{n}.html ← pages/scaffold-{n}.mdx (its example fence)
  const app = STANDALONE_APPS.find((s) => r === standaloneAppFile(s));
  if (app) return `documentation/pages/${app}.mdx`;
  // full-screen documents: full-{n}.html ← pages/{n}.mdx (its example fence)
  const doc = STANDALONE_DOCS.find((s) => r === standaloneDocFile(s));
  if (doc) return `documentation/pages/${doc}.mdx`;
  // pages: {n}.html ← pages/{n}.mdx
  if (r.endsWith('.html')) return `documentation/pages/${r.replace(/\.html$/, '')}.mdx`;
  return null;
}

/** The first ```html example fence of a page - the markup a standalone deck /
 *  full-screen scaffold page is generated from (null when the page has none). */
export function exampleFence(mdx: string): string | null {
  return mdx.match(/^```html example[^\n]*\n([\s\S]*?)^```$/m)?.[1] ?? null;
}

/** The app name of a scaffold page slug (`scaffold-messenger` → `messenger`) -
 *  its bundle is dist/apps/{name}.css + .js. */
export const appName = (slug: string): string => slug.replace(/^scaffold-/, '');
