/**
 * Why: the minify pass (scripts/minify.ts) and tsc (sourceMap) write derived
 * twins next to every shipped file. verify's `dist 1:1` orphan check, the
 * `minified artifacts` gate and the fingerprint hashing in inputs.ts all need
 * to recognize those as GENERATED, not orphans. Pure module (no fs/native
 * bindings) so tests/minify.test.ts can pin the contract in browser mode —
 * same split as scripts/lib/changelog.ts.
 */

/** Files derived from a source file: minified twins + JavaScript source maps. */
export const DERIVED_ARTIFACT = /\.(min\.css|min\.js|js\.map)$/;

/**
 * The single-file bundle (scripts/bundle.ts → minify.ts twins). These three
 * are generated yet NOT matched by DERIVED_ARTIFACT: all.css/all.js have no
 * src/ counterpart at all, and all.min.css.map is the system's only CSS source
 * map (the regex predates it). verify's `dist 1:1` orphan check allow-lists
 * them next to STATS_FILE. Kept OUT of isDerivedArtifact: minify.ts uses that
 * to skip re-minifying twins, and all.js/all.css must still be minified.
 */
export const BUNDLE_ARTIFACTS: ReadonlySet<string> = new Set([
  'components/all.css',
  'components/all.js',
  'components/all.min.css.map',
  // core.js = morph + query + shared, built by bundle.ts from src/core (§2.3);
  // its .js.map / .min.* twins are DERIVED_ARTIFACT matches already
  'components/core.js',
  // core.css = the 4 theme util sheets concatenated by bundle.ts
  // (plans/core-bundle.md) — generated, no src/ counterpart; its
  // .min.css/.min.css.map twins match DERIVED_ARTIFACT already
  'components/core.css',
  'components/core.min.css.map',
  // per-release provenance notice (§6): generated by bundle.ts next to the
  // runtime bundles it documents; has no src/ counterpart by design
  'components/NOTICE.txt',
]);

/** True for `x.min.css`, `x.min.js`, `x.js.map` and `x.min.js.map`. */
export function isDerivedArtifact(relPath: string): boolean {
  return DERIVED_ARTIFACT.test(relPath);
}

/**
 * Every shipped component file must have its minified twin (CSS: one; JS: min
 * + both source maps, per AGENTS.md — the Installation page advertises them,
 * so a missing twin is user-facing breakage). `present` = dist-relative paths
 * that exist non-empty. Returns human-readable problem lines; empty = OK.
 */
export function minifyArtifactProblems(present: ReadonlySet<string>): string[] {
  const problems: string[] = [];
  for (const rel of present) {
    const m = rel.match(/^components\/([^/]+)\/\1\.(css|js)$/);
    if (!m) continue;
    // strip exactly `.{ext}` (3 or 4 chars) — a fixed slice(0,-4) would eat a
    // character of every .js component name
    const base = rel.slice(0, -(m[2].length + 1));
    const required =
      m[2] === 'css'
        ? [`${base}.min.css`]
        : [`${base}.min.js`, `${base}.js.map`, `${base}.min.js.map`];
    for (const need of required) if (!present.has(need)) problems.push(`dist/${need} missing`);
  }
  // core.js is a top-level bundle artifact (no component folder) but ships
  // the same min twins — consumers load core.min.js exactly like all.min.js
  if (present.has('components/core.js')) {
    for (const need of ['components/core.min.js', 'components/core.js.map', 'components/core.min.js.map']) {
      if (!present.has(need)) problems.push(`dist/${need} missing`);
    }
  }
  // core.css likewise: min twin + its map (bundle.ts concat → minify.ts)
  if (present.has('components/core.css')) {
    for (const need of ['components/core.min.css', 'components/core.min.css.map']) {
      if (!present.has(need)) problems.push(`dist/${need} missing`);
    }
  }
  return problems.sort();
}
