/**
 * The component type-check ratchet (scripts/lib/type-check.ts): tsc errors per
 * file under tsconfig.components.json. Only ever lowered - verify fails when a
 * count rises (a written type does not hold) and when it falls (lower it here).
 */
export const TYPE_BASELINE: Readonly<Record<string, number>> = {
  "src/components/accordion/accordion.ts": 11,
  "src/components/alert-dialog/alert-dialog.ts": 11,
  "src/components/autocomplete/autocomplete.ts": 38,
  "src/components/avatar/avatar.ts": 9,
  "src/components/bibtex/bibtex.ts": 12,
  "src/components/border-layout/border-layout.ts": 19,
  "src/components/calendar/calendar.ts": 35,
  "src/components/carousel/carousel.ts": 17,
  "src/components/code-example/code-example.ts": 39,
  "src/components/color-picker/color-picker.ts": 13,
  "src/components/combobox/combobox.ts": 10,
  "src/components/command/command.ts": 22,
  "src/components/context-menu/context-menu.ts": 18,
  "src/components/countdown/countdown.ts": 15,
  "src/components/data-grid/data-grid.ts": 51,
  "src/components/data-tree/data-tree.ts": 22,
  "src/components/diagram/diagram.ts": 66,
  "src/components/dialog/dialog.ts": 11,
  "src/components/diff/diff.ts": 26,
  "src/components/dropdown/dropdown.ts": 23,
  "src/components/file-input/file-input.ts": 28,
  "src/components/image/image.ts": 14,
  "src/components/menubar/menubar.ts": 13,
  "src/components/navigation-menu/navigation-menu.ts": 5,
  "src/components/number-input/number-input.ts": 22,
  "src/components/otp-input/otp-input.ts": 9,
  "src/components/panel/panel.ts": 26,
  "src/components/popover/popover.ts": 5,
  "src/components/presentation/presentation.ts": 1,
  "src/components/product-showcase/product-showcase.ts": 6,
  "src/components/progress/progress.ts": 24,
  "src/components/property-grid/property-grid.ts": 42,
  "src/components/questionnaire/questionnaire.ts": 127,
  "src/components/radial-progress/radial-progress.ts": 11,
  "src/components/search-filter/search-filter.ts": 13,
  "src/components/session/session.ts": 20,
  "src/components/sheet/sheet.ts": 12,
  "src/components/sidebar/sidebar.ts": 21,
  "src/components/slider/slider.ts": 21,
  "src/components/sortable/sortable.ts": 34,
  "src/components/table/table.ts": 23,
  "src/components/tabs/tabs.ts": 24,
  "src/components/theme-switcher/theme-switcher.ts": 7,
  "src/components/toast/toast.ts": 20,
  "src/components/toggle-group/toggle-group.ts": 9,
  "src/components/toggle/toggle.ts": 4,
  "src/components/toolbar/toolbar.ts": 7,
  "src/components/tooltip/tooltip.ts": 13,
  "src/components/tree-view/tree-view.ts": 47,
  "src/components/typewriter/typewriter.ts": 11,
  "src/components/virtual-list/virtual-list.ts": 37,
  "src/components/window/window.ts": 23,
};
