/**
 * The component type-check ratchet (scripts/lib/type-check.ts): tsc errors per
 * file under tsconfig.components.json. Only ever lowered - verify fails when a
 * count rises (a written type does not hold) and when it falls (lower it here).
 */
export const TYPE_BASELINE: Readonly<Record<string, number>> = {
  "src/components/actions/toggle-group/toggle-group.ts": 9,
  "src/components/actions/toggle/toggle.ts": 4,
  "src/components/actions/toolbar/toolbar.ts": 7,
  "src/components/application/border-layout/border-layout.ts": 19,
  "src/components/application/panel/panel.ts": 26,
  "src/components/application/property-grid/property-grid.ts": 42,
  "src/components/application/sidebar/sidebar.ts": 21,
  "src/components/application/window/window.ts": 23,
  "src/components/big-data/autocomplete/autocomplete.ts": 38,
  "src/components/big-data/data-grid/data-grid.ts": 51,
  "src/components/big-data/data-tree/data-tree.ts": 22,
  "src/components/big-data/virtual-list/virtual-list.ts": 37,
  "src/components/chat/session/session.ts": 20,
  "src/components/data-display/avatar/avatar.ts": 9,
  "src/components/data-display/calendar/calendar.ts": 35,
  "src/components/data-display/carousel/carousel.ts": 17,
  "src/components/data-display/countdown/countdown.ts": 15,
  "src/components/data-display/diff/diff.ts": 26,
  "src/components/data-display/image/image.ts": 14,
  "src/components/data-display/sortable/sortable.ts": 34,
  "src/components/data-display/table/table.ts": 23,
  "src/components/data-display/tree-view/tree-view.ts": 47,
  "src/components/diagrams/diagram/diagram.ts": 66,
  "src/components/feedback-status/alert-dialog/alert-dialog.ts": 11,
  "src/components/feedback-status/progress/progress.ts": 24,
  "src/components/feedback-status/radial-progress/radial-progress.ts": 11,
  "src/components/feedback-status/toast/toast.ts": 20,
  "src/components/forms-inputs/color-picker/color-picker.ts": 13,
  "src/components/forms-inputs/combobox/combobox.ts": 10,
  "src/components/forms-inputs/file-input/file-input.ts": 28,
  "src/components/forms-inputs/number-input/number-input.ts": 22,
  "src/components/forms-inputs/otp-input/otp-input.ts": 9,
  "src/components/forms-inputs/search-filter/search-filter.ts": 13,
  "src/components/forms-inputs/slider/slider.ts": 21,
  "src/components/navigation/dropdown/dropdown.ts": 23,
  "src/components/navigation/menubar/menubar.ts": 13,
  "src/components/navigation/navigation-menu/navigation-menu.ts": 5,
  "src/components/navigation/tabs/tabs.ts": 24,
  "src/components/navigation/theme-switcher/theme-switcher.ts": 7,
  "src/components/overlays/accordion/accordion.ts": 11,
  "src/components/overlays/command/command.ts": 22,
  "src/components/overlays/context-menu/context-menu.ts": 18,
  "src/components/overlays/dialog/dialog.ts": 11,
  "src/components/overlays/popover/popover.ts": 5,
  "src/components/overlays/sheet/sheet.ts": 12,
  "src/components/overlays/tooltip/tooltip.ts": 13,
  "src/components/papers/bibtex/bibtex.ts": 12,
  "src/components/presentations/presentation/presentation.ts": 1,
  "src/components/primitives/typewriter/typewriter.ts": 11,
  "src/components/questionnaire/questionnaire/questionnaire.ts": 127,
  "src/components/website/product-showcase/product-showcase.ts": 6,
  "src/components/wysiwyg-editors/code-example/code-example.ts": 39,
};
