#!/usr/bin/env node
/**
 * Why: dist/documentation/ is produced ONLY by defuss-ssg from the MDX pages
 * and TSX components in src/documentation/. defuss-ssg pulls in uWebSockets.js
 * through its serve machinery, which ships Node-only native binaries
 * (engines ^20.19 || >=22.12) - so this script runs under `node`, not bun
 * (Node ≥23 strips the TypeScript types natively; keep the syntax erasable).
 *
 * Steps: compile the client runtime (runtime/*.ts → public/js/, tsc strips
 * types), then render every pages/*.mdx into dist/documentation/.
 */
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { build } from 'defuss-ssg';
import { STANDALONE_DECKS, standaloneDeckFile } from './lib/docs-ssg.ts';

const ROOT = join(import.meta.dirname, '..');
const DOCS = join(ROOT, 'src', 'documentation');

// 1. client runtime TS → public/js/ (the SSG build copies public/ verbatim)
const tsc = spawnSync('bunx', ['tsc', '-p', join(ROOT, 'tsconfig.docs-runtime.json')], {
  cwd: ROOT,
  stdio: 'inherit',
});
if (tsc.status !== 0) process.exit(tsc.status ?? 1);

// 2. components read repo files (component sources, skills, stats.json) at
//    build time - the SSG copies the project into .ssg-temp, so pin the root
process.env.DEFUSS_SHADCN_ROOT = ROOT;

const status = await build({
  projectDir: DOCS,
  mode: 'build',
  debug: process.argv.includes('--debug'),
});
if (status.code !== 'OK') {
  console.error('defuss-ssg build failed:', status.message);
  process.exit(1);
}
console.log('dist/documentation/ rendered by defuss-ssg');

// 3. standalone decks: pages that embed a deck elsewhere (the Getting Started
//    rail shows the flagship deck) iframe a chrome-free page generated from
//    the deck page's OWN example fence - one source, no second copy to drift.
//    Same stylesheet chain the CodeExample sandbox mirrors, then all.js.
const { readFileSync, writeFileSync } = await import('node:fs');
for (const slug of STANDALONE_DECKS) {
  const mdx = readFileSync(join(DOCS, 'pages', `${slug}.mdx`), 'utf8');
  const fence = mdx.match(/^```html example[^\n]*\n([\s\S]*?)^```$/m);
  if (!fence) {
    console.error(`standalone deck ${slug}: no \`\`\`html example fence in pages/${slug}.mdx`);
    process.exit(1);
  }
  const title = (mdx.match(/^title:\s*"([^"]*)"/m)?.[1] ?? slug).replace(/[<>&"]/g, '');
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex" />
<title>${title}</title>
<!-- generated by scripts/build-docs.ts from pages/${slug}.mdx (the deck page's example fence) - never edit -->
<link rel="stylesheet" href="../theme/utils/default-semantic-tokens.css" />
<link rel="stylesheet" href="../theme/utils/sizing.css" />
<link rel="stylesheet" href="../theme/utils/layout.css" />
<link rel="stylesheet" href="../theme/utils/accessibility.css" />
<link rel="stylesheet" href="../theme/utils/shapes.css" />
<link rel="stylesheet" href="css/docs-theme.css" />
<link rel="stylesheet" href="css/docs-utilities.css" />
<link rel="stylesheet" href="../components/all.css" />
<style>html, body { margin: 0; background: transparent; } body { overflow: hidden; }</style>
</head>
<body>
${fence[1].trimEnd()}
<script type="module" src="../components/all.js"></script>
</body>
</html>
`;
  writeFileSync(join(ROOT, 'dist', 'documentation', standaloneDeckFile(slug)), html);
  console.log(`standalone deck → dist/documentation/deck-${slug}.html`);
}
